packages:
  - apps/discord-radio
  - packages/config-eslint
  - packages/config-typescript

allowBuilds:
  '@discordjs/opus': false
  '@swc/core': true
  cbor-extract: false
  esbuild: true
  protobufjs: true

verifyDepsBeforeRun: warn
